config/routes.rb
Rails.application.routes.draw do
  root 'exchanges#dashboard'
  get 'exchanges/dashboard'
  resources :exchanges

end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  validates :recipient, presence: true
  def set_balance(current_balance)
    self.balance ||= 0
    if self
      self.balance = current_balance + credit if credit
      self.balance = current_balance - debit if debit
    end
  end

  def self.current_balance
    self.last.balance rescue 0
  end

  def self.current_month_expenditures
    this_months_exchanges = self.where("to_char(created_at, 'MM') = ?", Time.now.utc.strftime("%m"))
    this_months_exchanges.empty? ? 0 : this_months_exchanges.sum('debit')
  end

  def self.current_month_biggest_expense
    this_months_exchanges = self.where("to_char(created_at, 'MM') = ?", Time.now.utc.strftime("%m"))
    this_months_exchanges.empty? ? 0 : this_months_exchanges.maximum('debit')
  end

  def self.current_month_number_exchanges
    this_months_exchanges = self.where("to_char(created_at, 'MM') = ?", Time.now.utc.strftime("%m")).count
  end

  def self.last_month_expenditures
    last_months_exchanges = self.where("to_char(created_at, 'MM') = ?", (Time.now.utc.strftime("%m").to_i-1).to_s)
    last_months_exchanges.empty? ? 0 : last_months_exchanges.sum('debit')
  end

  def self.last_month_number_exchanges
    self.where("created_at BETWEEN ? AND ?", (Time.now - 1.month).beginning_of_month, (Time.now - 1.month).end_of_month).count
  end

  def self.biggest_expense
    self.maximum('debit')
  end

  def self.chastise_overdrafts
    # output = ""
    # if self.current_balance < 0
    #   output = "YOU HAVE OVERDRAFTED! HOW DARE YOU NOT HAVE ENOUGH MONEY! "
    #   output += "YOUR FRIENDS, FAMILY, AND COWORKERS HAVE BEEN ALERTED OF YOUR NEGLIGENCE!"
    # end
    # output

    output = ""
    if self.current_balance < 0
      choice = rand(1..3)
      case choice
      when 1
        output = "YOU'RE NOT YOUR JOB. YOU'RE NOT HOW MUCH MONEY YOU HAVE IN THE BANK. WHICH IS GOOD BECAUSE YOU HAVE NONE."
      when 2
        output = "THE THINGS YOU OWN END UP OWNING YOU. LUCKILY, YOU OWN NOTHING."
      when 3
        output = "IT'S ONLY AFTER WE'VE LOST EVERYTHING THAT WE'RE FREE TO DO ANYTHING. WELL, LOOKS LIKE YOU'RE FREE."
      end
    end
    output
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_exchange, only: [:show, :edit, :update, :destroy]

  # GET /exchanges
  def index
    @exchanges = Exchange.all
  end

  # GET /exchanges/dashboard
  def dashboard
    @exchanges = Exchange.all
  end

  # GET /exchanges/1
  def show
  end

  # GET /exchanges/new
  def new
    @exchange = Exchange.new
  end

  # GET /exchanges/1/edit
  def edit
  end

  # POST /exchanges
  def create
    @exchange = Exchange.new(exchange_params)
    current_balance = Exchange.current_balance
    @exchange.set_balance(current_balance)

    if @exchange.save
      redirect_to exchanges_path, notice: 'Exchange was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /exchanges/1
  def update
    if @exchange.update(exchange_params)
      redirect_to exchanges_path, notice: 'Exchange was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /exchanges/1
  def destroy
    @exchange.destroy
    redirect_to exchanges_url, notice: 'Exchange was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exchange
      @exchange = Exchange.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def exchange_params
      params.require(:exchange).permit(:recipient, :credit, :debit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title = '')
		base_title = "Bank of Tyler"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/_form.html.erb
<%= form_for(@exchange) do |f| %>
  <% if @exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
      <% @exchange.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipient %><br>
    <%= f.text_field :recipient %>
  </div>
  <div class="field">
    <%= f.label :credit %><br>
    <%= f.text_field :credit %>
  </div>
  <div class="field">
    <%= f.label :debit %><br>
    <%= f.text_field :debit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exchanges/_row.html.erb
<tr>
  <td><%= e.recipient %></td>
  <td>$<%= number_with_precision(e.credit, precision: 2) %></td>
  <td>$<%= number_with_precision(e.debit, precision: 2) %></td>
  <td>$<%= number_with_precision(e.balance, precision: 2) %></td>
  <td><%= link_to 'Show', e %></td>
  <td><%= link_to 'Edit', edit_exchange_path(e) %></td>
  <td><%= link_to 'Destroy', e, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/exchanges/dashboard.html.erb
<% provide(:title, "Dashboard") %>
<div class="content">
  <p id="notice"><%= notice %></p>

  <h1 id="dash_h1">In Tyler We Trust</h1>
  <h3>One step closer to economic equilibrium</h3>

  <p>
    Current balance:
    $<%= number_with_precision(Exchange.current_balance, precision: 2) %>
  </p>

  <p>
    Amount spent this month:
    $<%= number_with_precision(Exchange.current_month_expenditures, precision: 2) %>
  </p>

  <p>
    Amount spent last month:
    $<%= number_with_precision(Exchange.last_month_expenditures, precision: 2) %>
  </p>

  <p>
    Biggest single expense this month:
    $<%= number_with_precision(Exchange.current_month_biggest_expense, precision: 2) %>
  </p>

  <p>
    Biggest single expense ever:
    $<%= number_with_precision(Exchange.biggest_expense, precision: 2) %>
  </p>

  <p>
    Total number of exchanges this month:
    <%= Exchange.current_month_number_exchanges %>
  </p>

  <p>
    Total number of exchanges last month:
    <%= Exchange.last_month_number_exchanges %>
  </p>

  <p>
    Create a new exchange:
    <%= link_to 'New Exchange', new_exchange_path %>
  </p>

  <p>
    View all exchanges:
    <%= link_to 'All Exchanges', exchanges_path %>
  </p>

  <span id="overdraft">
    <%= ENV["MY_VAR"] %>
  </span>

  <span id="overdraft">
    <%= Exchange.chastise_overdrafts %>
  </span>

  <p class="bottom"></p>
</div>

app/views/exchanges/edit.html.erb
<% provide(:title, "Edit") %>


<div class="content">
  <h1>Editing Exchange</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @exchange %> |
  <%= link_to 'Back', exchanges_path %>
</div>

app/views/exchanges/index.html.erb
<% provide(:title, "Index") %>


<div class="content">
  <p id="notice"><%= notice %></p>

  <h1>Listing Exchanges</h1>

  <table>
    <thead>
      <tr>
        <th>Recipient</th>
        <th>Credit</th>
        <th>Debit</th>
        <th>Balance</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @exchanges.each do |exchange| %>
        <%= render partial:"row", locals:{e: exchange} %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Exchange', new_exchange_path %>

  <p><%= link_to 'Dashboard', root_path %></p>

  <p class="bottom"></p>

</div>

app/views/exchanges/new.html.erb
<% provide(:title, "New") %>

<div class="content">

  <h1>New Exchange</h1>

  <%= render 'form' %>

  <%= link_to 'Back', exchanges_path %>
  <p class="bottom"></p>

</div>

app/views/exchanges/show.html.erb
<% provide(:title, "Show") %>

<div class="content">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Recipient:</strong>
    <%= @exchange.recipient %>
  </p>

  <p>
    <strong>Credit:</strong>
    <%= @exchange.credit %>
  </p>

  <p>
    <strong>Debit:</strong>
    <%= @exchange.debit %>
  </p>

  <p>
    <strong>Balance:</strong>
    <%= @exchange.balance %>
  </p>

  <%= link_to 'Edit', edit_exchange_path(@exchange) %> |
  <%= link_to 'Back', exchanges_path %>
  <p class="bottom"></p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>